name: Compile Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"
          brew install ldid xz git
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          cd $THEOS/sdks
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/*.sdk .
          rm -rf sdks-master master.zip

      - name: Compile
        run: |
          export THEOS=~/theos
          export PATH=$THEOS/bin:$PATH
          cd "${{ github.workspace }}"
          make clean
          make package
          for f in packages/*.deb; do mv "$f" AwemeBypass.deb; break; done

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: AwemeBypass
          path: AwemeBypass.deb
